apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: notiflex-secrets
  namespace: notiflex
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: projects/project-b3c5c78c-8a5c-4e47-9fe/secrets/valkey-password/versions/latest
        path: valkey-password
