apiVersion: v1
kind: ServiceAccount
metadata:
  name: notiflex-api
  namespace: notiflex
  annotations:
    iam.gke.io/gcp-service-account: notiflex-secrets@project-b3c5c78c-8a5c-4e47-9fe.iam.gserviceaccount.com
